# Generated by Django 5.2.6 on 2025-10-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(default="En attente", max_length=50),
        ),
        migrations.AddField(
            model_name="service",
            name="adresse",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="publier",
            field=models.BooleanField(default=False),
        ),
    ]
