# Generated by Django 5.2.7 on 2025-10-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_reservation_status_service_adresse_service_publier"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/images/"
            ),
        ),
    ]
