# Generated by Django 5.2.7 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="nom_client",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
