# Generated by Django 5.2.7 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models


def populate_type_service(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    TypeService = apps.get_model("services", "TypeService")

    for service in Service.objects.all().iterator():
        nom_service = (service.nom_service or "").strip()
        if not nom_service:
            continue
        type_service, _ = TypeService.objects.get_or_create(nom=nom_service)
        service.type_service_id = type_service.id
        service.save(update_fields=["type_service"])


def clear_type_service(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    Service.objects.update(type_service=None)


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_reservation_nom_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "type de service",
                "verbose_name_plural": "types de service",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="type_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="services.typeservice",
            ),
        ),
        migrations.RunPython(populate_type_service, clear_type_service),
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_client", models.CharField(max_length=120)),
                ("note", models.PositiveSmallIntegerField(choices=[(1, "1/5"), (2, "2/5"), (3, "3/5"), (4, "4/5"), (5, "5/5")])),
                ("commentaire", models.TextField(blank=True)),
                ("visible", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "avis",
                "verbose_name_plural": "avis",
                "ordering": ["-date_creation"],
            },
        ),
    ]
