# Generated by Django 5.2.7 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_typeservice_avis_service_type_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestataire",
            name="photo_profil",
            field=models.ImageField(
                blank=True, null=True, upload_to="prestataires/profils/"
            ),
        ),
    ]
